# -*- coding: utf-8 -*-
"""Untitled325.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJ-zj9ferba73f1ig0IEUG1xFgOkC6iW

## 제목: 고차원 데이터 → (Embedding) → ChromaDB 저장 → Nomic Atlas Project → 인터랙티브 시각화

데이터 → Embedding 생성

데이터가 수치형이면 OpenAI Embedding, SentenceTransformers, nomic-embed-text 등 사용

각 데이터 포인트를 고차원 벡터로 표현

ChromaDB에 저장
"""

import chromadb
from chromadb.utils import embedding_functions

client = chromadb.Client()
collection = client.create_collection("3d_data")

for idx, vector in enumerate(embedding_vectors):
    collection.add(ids=[str(idx)], embeddings=[vector], metadatas=[{"label": int(y[idx])}])

"""nomic으로 시각화

Nomic은 UMAP, HDBSCAN 등 비선형 차원 축소를 활용

대규모 데이터도 효율적으로 클러스터링 시각화
"""

from nomic import AtlasProject

project = AtlasProject(
    name="3D_Data_Clustering",
    description="High-dimensional clustering visualization",
    data=embedding_vectors,
    metadata=[{"label": int(lbl)} for lbl in y]
)

project.create_index()   # Embedding index 생성
project.map_embeddings() # 시각화용 매핑
project.launch_app()     # nomic web UI에서 시각화 확인

