# -*- coding: utf-8 -*-
"""Untitled326.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2x782cJhXtMyTeXKtEpAajg8lmMCS9V
"""

!pip uninstall nomic -y
!pip install 'nomic[embed]' --upgrade

import nomic

# Run nomic login to configure your API key
# You will need to replace 'YOUR_NOMIC_API_TOKEN' with your actual token
# This may no longer open a browser window for interactive login based on the error
nomic.login(token='nk-_')

print("NOMIC API key configuration initiated. Please replace 'YOUR_NOMIC_API_TOKEN' with your actual token.")

import numpy as np
from nomic import atlas

# 샘플 데이터
n_samples = 20
n_classes = 1000
np.random.seed(42)
softmax_outputs = np.random.dirichlet([0.1]*n_classes, size=n_samples)
metadata = [{"image_id": f"img_{i}", "pred_class": int(i % 10)} for i in range(n_samples)]

# ✅ 데이터 구조 수정 - embeddings and metadata will be passed separately

# Nomic Atlas 맵핑
# Passing embeddings and metadata as separate arguments to map_data
result = atlas.map_data(
    embeddings=softmax_outputs, # Pass NumPy array directly to embeddings parameter
    data=metadata, # Pass metadata list of dictionaries to data parameter
    id_field='image_id', # Use image_id as the id_field from metadata
    # embeddings_field='embeddings', # Not needed when passing embeddings separately
    # name="Imagenet_Softmax_Visualization", # Removed name based on previous error
    # description="1000-class softmax clustering visualization" # Removed description based on previous error
)

print("🔗 View project:", result['url']) # Use result['url'] for the URL